language: node_js
node_js:
- '6'
- '5'
- '4'
install:
- npm install
deploy:
  provider: npm
  email:
    secure: I/uyT7GGtPrbnsec/Ho1P6U7T5ewPIc0y+Gcvl+IGuuu/yVrrLYhxI5gYksEkwkcBaftbKZaLiKYreKRkDL+BKutzSDExbtpaWBKbgsLD7Ou4sUoEgCZGeaH9KyE9/3SicVTsK0rOsfF96Ov6CWV/zeGXxQiABGQ5YpCpN2IwGRkelhGOCh6hYpIwt1GPhe/TVRmKAdZk9e3SMBreH+kNVdfewz3koy4HWtK+LhylYcXGvAilZLF3ZZEO4qJBi1G4eL7DOYApJcc8TZWCamntQCK5fpUwM+B9KVSAH0Fc6qeOBA+qTVLOezJsPgr0NXxtoo0kK8pIV/qS6qCQTohyTxhbQTXVUn2qxpifVS7A2BFLkDshhpotq1xy84muzIVZJzHxEDfxXTo8RJaFT2M6ikHQL+DYgw/FWONkpU/h2lK0T4sI86R3YWXIc+wojg+TCFunDkPWDzOHxeOA/lB3WwQDGc06LTJLRTMcQXVpQGcnVBk4mOpKpaV2K4bljwj6fzlwUZq6yrR8181gBGzJRVhYVc9zDPlVHiQ9M6jppnSAcsuYB3lrHdZtBW8ujpm3RAjwrEDyp7kC8bJPUNjuI7UtVO1CsNLaWuFXWiOhK1bsxIpQVd+N50kM93j4ShLUVt7vhrBb2NlO6Fff6JNuAxdfT4pcwQ3omVqRGHnEjU=
  api_key:
    secure: U/BQ9P8d0cezlQFKsbet3xtvsfx1QCWCujiCHzD7QlZTeRJc6mJxPIi2Hpchw38dGTo6QjvHlU41FjL14ULcmbzmVPLk01Ho71Y6DF1m/JQfsTZe9YSb1dkWy+JrJxQMcrrqRn9ljbgxJWsQjhOLe8rt25kvQWE5Gt6qkdwdGUVErvGTPOn8T46AwnMyC49NSoiMnKGxIrd1viyqJu2IT9Rc8PYuKgaG7wuBWKhRdZz9wgCXuWqw4Xl7dZgLZLkWADTgRX4xIJ2+cs0vr+lmQ2VwAEaOBA0841mO7iKE+9B0FABPATC8eVGoFAjz0L/JEhYLdKliPZVWkQPUR9tbIfmaA5NqAqM5Ss1hC7GaFLLYQlR/MzgSMe1O6+vmiTX5bIX8XnQQ3FGsEvQhFdfAlB4Z2DDd7bP1nnHJF5pqbyCngzOHw1sJ/TQ+a1gfnVQQGiuu2XqkzKtEShOmxnd35hvhawPpfvs8nYp6Sq6n/03dHOpg9W9g49zpvxbC971h2EDAOFpPgNLxWeC1A3349III+0b2O2xPDXanGLb3IPgcdZ/+FKHIVT93QSEREIi35aUeWEXIr8/vXhv3qPTWh8S4RInisLlWeov/33iTtJhbOZgeOKNK2+IjE6yRybVLtXgNcdhdbTVehf9IazGigjyWYMd/mk6vW++Lm5M4K4M=
  skip_cleanup: true
  tag: latest
  on:
    node: '6'
    tags: true
